name: Github Pages
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Download compiler
        run: |
          python3 download_compiler.py
      - name: Compile
        run: |
          ./compile.sh -m -s -d
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload scripts
        uses: actions/upload-pages-artifact@v1
        with:
          path: js
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
